### ISSUE TITLE
Integrate to IDE

### ISSUE THREAD

**Issue by SebCanet** [gasolin/BlocklyDuino#103]
Hi,
I've finished a jar file to integrate BlocklyDuino as a 'tool', which permit to send command from Blockly to IDE.
Maybe we should create another repo for that ?

**Comment by gasolin** [comment]
sure :+1: I can create one, which project name do you prefer?

**Comment by SebCanet** [comment]
What do you think of 'BlocklyDuino_IDE_plugin' ?

**Comment by gasolin** [comment]
I created blank `BlocklyDuino_IDE_plugin` repo in https://github.com/BlocklyDuino/BlocklyDuino_IDE_plugin and add you as admin. You can add source there. Feel free to ping me if you need any help.

**Comment by talalz94** [comment]
@gasolin I having trouble uploading the code generated using your tool, onto the arduino board. I am aware that we are to create a webserver using the Aruidno IDE environment. Can you guide me on how I can achieve that or I can use the above mention plugin to directly send the code to the Arduino IDE for uploading purposes? 

Thanks

**Comment by SebCanet** [comment]
That's finished !
I created 2 folders:
- sources: with files created with NetBeans IDE
- BlocklyDuinoPlugin: folder contains everything, just have to copy it in ArduinoIDEfolder\tools

I started a minimal Readme, you just have to had explanations.
