### ISSUE TITLE
Localization system

### ISSUE THREAD

**Issue by philippejadin** [gasolin/BlocklyDuino#110]
Continuing the discussion from  https://github.com/BlocklyDuino/BlocklyDuino/pull/108#issuecomment-453732776

There are several options for translations : 
- use the same syntax in blocks as blockly, with code to convert this syntax to the correct language at runtime. This is the most logical way, but we need to figure out how to parse our own blocks in the "boot" process of blockly, which is made a bit difficult because the files are agregated/compiled/minified/optimized using their python script (I'd prefer a more standard pipeline but well :-))
- use a translate function which add some smartness but is also specific to our use.

I'll post a concept here when I'll have time to make it. I guess this is somewhat lower priority.

**Comment by gasolin** [comment]
I think at the v2 begining phase it's not hard to patch
https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/msg/js/en.js
to add new strings and build them with blockly's build.py script. We can import the same msg file for l10n support

And then we can make a script to do something similar to generate the msg patch file (git diff) and a script to apply the diffs (git apply) 

I just made a general diff-patch script https://www.npmjs.com/package/file-patch that might help

first install it via `npm install file-patch`

Then copy `blockly/msg/js/en.js` to `blockly/msg/js/en-mod.js` and add a line
at the bottom
```js
Blockly.Msg["ARDUINO_TEST"] = "test";
```

then we can use `file-diff` command to generate a `.diff` file

```sh
./node_modules/.bin/file-diff blockly/msg/js/en.js blockly/msg/js/en-mod.js
txt  @@ -32561,12 +32561,50 @@
 %22%5D = %22310%22;%0A
+Blockly.Msg%5B%22ARDUINO_TEST%22%5D = %22test%22;%0A

diff file is saved to ...BlocklyDuino/blockly/msg/js/en.js.diff
```

Then we can patch the origin `en.js` with generated `en.js.diff` file

```sh
./node_modules/.bin/file-patch ../BlocklyDuino/blockly/msg/js/en.js.diff ../BlocklyDuino/blockly/msg/js/en.js
```

now `en.js` is the same as `en-mod.js`.

The tool is based on https://www.npmjs.com/package/diff-match-patch (diff-match-patch is also created by Neil, the blockly's creator ;) )

**Comment by SebCanet** [comment]
What I'm thinking is about easyness. The real success of Blockly (upon Scratch like, made with Flash),a nd why I choosed to work on it is the easibility to change anything, just open with a text editor and that's all. That's why many teachers use my version, enhance it, etc.
I think diff, merge, patch, compile are not user-friendly for newbies like french teacher...
