### ISSUE TITLE
can't find the given path as Step 4

### ISSUE THREAD

**Issue by kfkafka** [gasolin/BlocklyDuino#113]
![Screenshot (2)](https://user-images.githubusercontent.com/62951834/78046952-6b8dd500-7395-11ea-96e8-89a1c705c828.png)
as mentioned in step 4. i cant find the folder 'apps'. Please help.

**Comment by SebCanet** [comment]
Hi,
did you check you have the same folders as in the repository?
When you unzip, you should have folders like this : "BlocklyDuino-master/blockly/apps/blocklyduino/"

**Comment by kfkafka** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/62951834/78452752-c2075600-76aa-11ea-8f43-48e9520aebdd.png)
Hi,
yes, I have checked, there is no folder in the repository and the unzipped folder

**Comment by SebCanet** [comment]
Hi,
it seems you have too many blockly installed in the same folder :-D
When you unzip BlocklyDuino, you have folders like this screen capture:
![Image 1](https://user-images.githubusercontent.com/6362199/78453184-5b753e80-7690-11ea-99c8-f2629651d26a.png)

In blue it's all the folders, in red it's what you have to open to find 'index.html'.

**Comment by kfkafka** [comment]
Okay, so would you please share the link to the right BlocklyDuino which would have the exact files

**Comment by SebCanet** [comment]
You could download : [https://github.com/BlocklyDuino/BlocklyDuino/archive/gh-pages.zip](https://github.com/BlocklyDuino/BlocklyDuino/archive/gh-pages.zip)
Or tes new version: [https://github.com/BlocklyDuino/BlocklyDuino-v2/archive/master.zip](https://github.com/BlocklyDuino/BlocklyDuino-v2/archive/master.zip)
