### ISSUE TITLE
Ultrasonic ranger block has only one pin option

### ISSUE THREAD

**Issue by DevT0ny** [gasolin/BlocklyDuino#114]
Ultrasonic ranger block has only one pin but there's no option for 2 pin type sensor.
Ping type sensor has 3 pins, 2 for supply 1 data pin but HC-SR04 sensor is most widely used and it has 4 pins 2 supply 2 data ( echo & trig pins ).
I found library where both  type is supported so please implement this.
https://github.com/ErickSimoes/Ultrasonic

**Comment by SebCanet** [comment]
Many thanks, that's a good idea. But this original project was only created for Grove sensors, that's why it has only pin block entry, the 2nde one ies automatically the next number.
Go to https://github.com/BlocklyDuino/BlocklyDuino-v2/issues/3
