### ISSUE TITLE
more grove in BlocklyDuino

### ISSUE THREAD

**Issue by Mohammadgeek** [gasolin/BlocklyDuino#119]
hello, I look at the Blocklyduino project but I need to work on more modules in the web server, and how to customize and increase grove for Blocklyduino, in this source code all modules only design at [Seeed Studio](https://www.seeedstudio.com/), what changes the source for customizing **another grove**?

**Comment by SebCanet** [comment]
Hello,
the original BlocklyDuino project is no longer maintained at all. I am currently working (when I have time...) on its reboot: BlocklyDuino2 (https://github.com/BlocklyDuino/BlocklyDuino-v2).
I don't have time to add blocks, I'm working on the background and the new features of Blockly.
If you're looking for a project with a lot of blocks, there are other projects like the one I did previously : Blockly@rduino (https://github.com/technologiescollege/Blockly-at-rduino).

I hope you find what you are looking for,
enjoy tests.
