### ISSUE TITLE
글상자 새로운 모드 관련 버그

### ISSUE THREAD

**Issue by jaewhi23** [gasolin/BlocklyDuino#30]
1. 글상자 새로운 모드의 내용 입력상자의 크기 조절이 가능합니다.
2. 오브젝트 추가 창에서 글상자 새로운 모드로 선택후 생성시 글상자의 내용이 적용이 안되고 '글상자'로 오브젝트가 생성됩니다.
https://entrykorea.slack.com/files/jaehwi/F04TT8BL8/record_2015_05_19_13_29_39_542.mp4

**Comment by gasolin** [comment]
Sorry I can't read korean, could you translate your issue to english?

**Comment by jaewhi23** [comment]
Oh, I'm sorry. I thought I was in other hub. My mistake. I'll close it!
