### ISSUE TITLE
incompatible arduino versions?

### ISSUE THREAD

**Issue by mjhoy** [gasolin/BlocklyDuino#6]
@gasolin I've been noticing a few things that don't work or are missing in this and I wonder if it has to do with different versions of arduino... which I'm not familiar enough with to know about, so I thought I'd ask.

First, if a procedure returns a value, it's return type is `Dynamic`... but this is not supported when I compile it (`error: 'Dynamic' does not name a type`).

Second, it is possible to make an analog write to certain digital out pins... 3, 5, 6, 9, 10, 11; but the `analogWrite` function only allows A0 through A5.

I've been tweaking things so they work for me; but I wonder, are these different on the Arduino you're using? If not I can perhaps write up some pull requests.

**Comment by SebCanet** [comment]
I created a way to chosse between Uno and Mega board, and created a 'PWM' section for pin choice.
If it's useful...

**Comment by gasolin** [comment]
Sure please provide PR so others could pick it if needed

**Comment by ltj2006** [comment]
**@mjhoy** Could you please tell me how to tweak the analogWrite to pin 3, 5, 6, 9, 10, 11 problem? Do you modify blocklyduino-code or C-Code in the Arduino-IDE?

**Comment by mjhoy** [comment]
@ltj2006 hmm, not sure, it's been so long and I've since lost any modifications I made. Perhaps it was fiddling with this line? https://github.com/gasolin/BlocklyDuino/blob/master/blockly/blocks/base.js#L112 Changing from a dropdown to a text input? Just guessing.

**Comment by ltj2006** [comment]
**@mjhoy** Ok, that's one way. Yesterday, I counldn't wait for your answer and I have studied the blocklyduino code and modified this line ( https://github.com/gasolin/BlocklyDuino/blob/master/blockly/generators/arduino.js#L78) to this:

analog : [["A0", "A0"], ["A1", "A1"], ["A2", "A2"], ["A3", "A3"], ["A4", "A4"], ["A5", "A5"], ["3", "3"], ["5", "5"], ["6", "6"], ["9", "9"], ["10", "10"], ["11", "11"]],

That works for me ;-)

**Comment by gasolin** [comment]
@ltj2006 provide the way to customize it. To keep it simple (not all boards support using pin 3, 5, 6, 9, 10, 11 as software PWM) I'd rather not put those pin in the BlocklyDuino
