### ISSUE TITLE
BlocklyDuino Daemon to flash code without copy/paste to Arduino IDE

### ISSUE THREAD

**Issue by gasolin** [gasolin/BlocklyDuino#7]
create a nodejs process that provide API interface and can write data to Arduino via inotool http://inotool.org/

So we don't need manually paste code to Arduino IDE

**Comment by gumbypp** [comment]
I have also been working on a solution to this problem (see https://github.com/gumbypp/BlocklyDuino).  It uses a local python web server to download the code using ino.  

I have also forked ino (see https://github.com/gumbypp/ino) to solve the 1.5.x path problem (it was actually solved by another user with a pending pull request to that repo) and add an option to skip the default include paths which was generating a command line too long error for me (on OS X Yosemite).

**Comment by gasolin** [comment]
@gumbypp Wow that's great to see a python server version! I had a version with `bottle.py` but in this case we even don't have to use the web framework. Would you consider send a pull request to merge it  back?

**Comment by stevoleeto** [comment]
@gumbypp @gasolin What's the best way to do this on Windows? Any help is greatly appreciated.

**Comment by gumbypp** [comment]
@gasolin I will submit a pull request soon.
@stevoleeto Unfortunately, ino doesn't work on Windows.  If the Arduino 1.5.x CLI works on Windows, it could probably be used instead of ino (the CLI doesn't work on OS X - at least as of 1.5.8).

**Comment by gasolin** [comment]
@gumbypp  saw the PR in #15 , would you like modify the change with my comment? It's fine that I can do that as well after merged.

**Comment by gumbypp** [comment]
@gasolin Thanks for the review - I made the suggested changes.

**Comment by gasolin** [comment]
fixed with #15
