### ISSUE TITLE
Traduction bluetooth block in french

### ISSUE THREAD

**Issue by jbet** [gasolin/BlocklyDuino#72]
French  traduction
![selection_155](https://cloud.githubusercontent.com/assets/5906988/14141555/1505b3ce-f680-11e5-8396-d3c576067c13.png)
"Lire" is not the rignt traduction
Could you change the block  bluetooth, by remplacing "lire" by "envoyer" as we seen on the spanish traduction.

Spanish traduction
![selection_156](https://cloud.githubusercontent.com/assets/5906988/14141592/59893e8a-f680-11e5-9f62-b46c381b0b1d.png)

Best regard

**Comment by carlosperate** [comment]
Are you sure you are using this BlocklyDuino? I believe there are no translation for the current blocks, and the Bluetooth block is a different colour. Apart from that the BlocklyDuiono version has "receive" first and then "send", which seems to be the opposite way displayed in your screenshot for both languages.

**Comment by jbet** [comment]
I use this.
http://www.technologiescollege.fr/blockly@rduino/?lang=fr

**Comment by carlosperate** [comment]
You will get better support in their repository then: https://github.com/technologiescollege/Blockly-at-rduino

**Comment by gasolin** [comment]
Yeah BlocklyDuino does not provide translation yet
