### ISSUE TITLE
Can BlocklyDuino achieve real-time controlling with Arduino by firmata protocol?

### ISSUE THREAD

**Issue by iszufu** [gasolin/BlocklyDuino#73]
In my case, BlocklyDuino can only generate arduino code and upload the code to an arduino board, rather than communicate with a board in real time. So, if I would like to make it happen, just like what [snap4arduino](http://s4a.cat/snap/) has done, what should I do?

**Comment by gasolin** [comment]
You'd better check johhny-five or other blockly tool to generate commands. BlocklyDuino is used to generate real arduino code.
