### ISSUE TITLE
arduino --upload returned 259

### ISSUE THREAD

**Issue by iszufu** [gasolin/BlocklyDuino#74]
When I upload the generated arduino code from blocklyduino page, the python server side shows this problem, what is this? BTW, the server has already found the right port and the directory that including arduino app.

**Comment by gasolin** [comment]
please attach the error log, thanks

**Comment by iszufu** [comment]
I had successfully uploaded the code to a Uno board when I closed the proxy software, thanks anyway.

**Comment by gasolin** [comment]
Glad you figure it out. Close the issue :)
