### ISSUE TITLE
New Blockly

### ISSUE THREAD

**Issue by rimish786** [gasolin/BlocklyDuino#75]
Hello Sir,
Earlier I was using Codevision Avr software to program microcontroller
I am making new blockly for microcontroller Atmega8, Atmega16, Atmega32
I am Successfully able to convert blockly code to C language.
I want to compile the c code now.
I need gcc-avr, avr-libc, binutils-avr and one programmer library to dump program into microcontroller
I got all above libraries except programmer to dump the code.
I want to know how to compile the code now means how to link our blockly and compiler and then to programmer.

**Comment by gasolin** [comment]
BlocklyDuino just redirect the compiling effort to Arduino IDE
